# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish"
baseURL = "https://kaszworkx.netlify.app"
defaultContentLanguage = "en"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

disqusShortname = 'kaszworkx'

enableRobotsTXT = true
paginate = 20
summaryLength = 11

buildDrafts = false
buildFuture = false

googleAnalytics = "G-PEDMYR1V0K"

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'always'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON", "htaccess"]

[outputFormats.htaccess]
  baseName = ""
  isPlainText = true
  mediaType = "text/htaccess"

[mediaTypes]
  [mediaTypes."text/htaccess"]
    suffixes = ["htaccess"]

[permalinks]
  archive = '/:section/:title/'
  about = '/:section/:title/'
  resources = '/:section/:title/'
  updates = '/:section/:title/'
  chapters = '/:section/:title/'
  posts = '/:section/:title/'

[module]

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false

