# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 10

[[main]]
  name = "beKnighted"
  weight = 20

[[main]]
  name = "Resources"
  parent = "beKnighted"
  pageRef = "resources"
  weight = 10

[[main]]
  name = "Chapters"
  parent = "beKnighted"
  pageRef = "chapters"
  weight = 20

[[main]]
  name = "Project Updates"
  parent = "beKnighted"
  pageRef = "updates"
  weight = 30

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 35

[[main]]
  name = "Archive"
  pageRef = "archive"
  weight = 40

#[[subnavigation]]
#  name = "Test"
#  pageRef = "tags/philosophical"
#  weight = 10

#[[main]]
#  name = "Merch"
#  url = "http://tee.pub/lic/qwSlWVBL5zc"
#  weight = 50

#[[main]]
#  name = "Test"
#  pageRef = "pagTest"
#  weight = 1000

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/KXzeno/"
  weight = 60

#[[main]]
#  identifier = "mastodon"
#  pre = "mastodon"
#  url = "https://masto.ai/@blowfish"
#  weight = 70

#[[main]]
#  identifier = "github"
#  pre = "github"
#  url = "https://github.com/nunocoracao/blowfish"
#  weight = 80


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Authors"
   pageRef = "authors"
   weight = 20