baseURL: "https://kasz.com/workx" 
languageCode: en-us
title: "KASZ"
theme: blowfish
Author: Kasz
enableEmoji: true

  #minify:
  #disableXML: true
  #minifyOutput: true
pluralizelisttitles: "false"

paginate: 3
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: true
ignoreErrors:
  - error-remote-getjson
sectionPagesMenu: main
params:
  noindex: false
  theme:
    palette: base16-dark
  about:
    title: WorKx 
    description: 'Unfiltered thoughts leaked out of my secluded possessions'
    logo: images/rice.svg
  socialLinks:
    - icon: fa-brands fa-github
      title: GitHub
      url: 'https://github.com/KXzeno?tab=projects'
    - icon: fa-solid fa-envelope
      title: Email
      url: 'mailto:kathekontelos@gmail.com'
    - icon: fa-brands fa-discord
      title: Discord
      url: 'https://discord.gg/evgWha8'
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
taxonomies:
  category: categories
  tag: tags
  series: series
markup:
  goldmark:
    renderer:
      unsafe: true
privacy:
  vimeo:
    disabled: false
    simple: true
  twitter:
    disabled: false
    enableDNT: true
    simple: true
  instagram:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true
services:
  instagram:
    disableInlineCSS: true
twitter:
  disableInlineCSS: true
