# File made in case needed for advanced control

[[redirects]]
	from = "/*"
	to = "/404/"
	status = 404

[build]
  command = "hugo"
  commandOrigin = "config"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.110.0"